
dag:
  dag_id: "dataform_to_dataproc_serverless_pipeline"
  schedule_interval: 0 6 * * *  # (daily at 6 AM)
  catchup:           False

dag_args:
  owner:      data-eng
  start_date: 01-01-2026
  retries:    1 
  retry_delay_sec: 300

dataform:
  enabled: true
  git_commitish: main
  tags:
    - users_per_city

dataproc:
  enabled: true
  job: users_per_city
  batch_timeout_minutes: 45

retries:
  count: 1
  delay_minutes: 5

alerts:
  email_on_failure: false
