batch_name: users-per-city

main_script: "dataproc/jobs/users_per_city.py"

source:
  dataset: gold
  table: gold_users_address

target:
  dataset: gold
  table: gold_users_per_city

write_mode: overwrite
