
env:

  env_name: dev
  project_id: dataengproj-500110
  region: us-central1
  scripts_bucket: gs://deloitte_assignment_dataproc_dev

  spark_session:
    app_name:                spark
    views_enabled:           True
    materialization_dataset: dataproc_materialization

  bigquery:
    # location: EU
    temp_bucket: gs://deloitte_assignment_dataproc_temp

