
dataproc_deploy:

  release:
    create_new: False
    requested_version: 'latest'  # unused when create_new == true
    assets:
    # define files to include/exclude in the release if create_new == true
    # should contain scripts for all jobs
    # path should be relative to repo root
      include:
        - dataproc/jobs/
      include_zipped:
        - dataproc/utils/
        - common/
        - configs/
    ignore_patterns:
      dirs:
        - __pycache__
      extensions:
        - "*.pyc"

  batch_kwargs: 
    pyspark:
      python_file_uris:
        - dataproc/utils.zip
      file_uris:
        - configs/project.yaml
        - configs/environments/dev.yaml
        - configs/dataproc/jobs/users_per_city.yaml
    runtime_config_properties:
      spark.sql.adaptive.enabled: True