environments:
  
  dev:
    
    project_id: dataengproj-500110
    
    buckets:
      data_storage: gs://deloitte-assignment-data
      dataproc_scripts: gs://deloitte_assignment_dataproc_dev
      dataproc_temp: gs://deloitte_assignment_dataproc_temp
    
    dataform:
      repository_id: DeloitteAssignment
      region: us-central1
      git_commitish: main
    
    dataproc:
      region: us-central1
