environments:
  
  dev:
    
    project_id: dataengproj-500110
    region:     us-central1

    buckets:
      data_storage:     gs://deloitte-assignment-data
      dataproc_scripts: gs://deloitte_assignment_dataproc_dev
      dataproc_temp:    gs://deloitte_assignment_dataproc_temp
      airflow_scripts:  gs://us-central1-deloitte-assign-fdde6010-bucket
    
    dataform:
      repository_id:   DeloitteAssignment
      git_commitish:   main
      service_account: 240983826854-compute@developer.gserviceaccount.com
    
    dataproc:
      release_version: latest  # release-20261003_154934-0d10a8b
      spark_session:
        app_name:      spark
        views_enabled: true
        materialization_dataset: spark_materialization

