pipelines:

  users_per_city:

    dag:
      dag_id:          "users-per-city"
      schedule:        null  # "@monthly"
      start_date:      "01-01-2026"
      catchup:         false
      max_active_runs: 1
      default_args:
        retries:                   0
        retry_delay:               120   # 2 minutes[sec]
        # retry_exponential_backoff: true  # 
        # max_retry_delay:           900   # 15 minutes [sec]

    tasks:
      - task_id:    compile_dataform
        operator:   DataformCreateCompilationResultOperator
        is_enabled: true

      - task_id:    silver_users
        operator:   DataformCreateWorkflowInvocationOperator
        is_enabled: true
        depends_on: [compile_dataform]
        params:
          workflow_invocation:
            invocation_config:
              included_targets:
                - schema: silver
                  name:   users
              transitive_dependencies_included: true

      - task_id:    silver_address
        operator:   DataformCreateWorkflowInvocationOperator
        is_enabled: true
        depends_on: [compile_dataform]
        params:
          workflow_invocation:
            invocation_config:
              included_targets:
                - schema: silver
                  name:   address
              transitive_dependencies_included: true
