dataproc_deploy:
  
  release:
    local_dir: "outputs/release"
    create_new: false
    requested_version: latest  # release-20261003_154934-0d10a8b
  assets:
    files:
      - dataproc/jobs/
      - .env
    python_packages:
    # Upload as .zip - Spark adds these files directly to the Python path (sys.path), imports modules directly from inside the compressed .zip file structure.
      - dataproc/
      - common/
    archive:
    # Upload as .zip - Spark automatically extracts the contents into the local filesystem (subdirectory named after the archive file - including the '.zip').
      - config/
  
  ignore_patterns:
    dirs:
      - __pycache__
    extensions:
      - .pyc
      - .zip
  